protocol: "CLAHE"
comment: "CLAHE(8x8 → 4x4)"
training:
  criterion:
    name: "CrossEntropyLoss"
  optimizer:
    name: "torch.optim.Adam"
    params:
      lr: 0.001
  scheduler:
    name: "torch.optim.lr_scheduler.StepLR"
    params:
      step_size: 10
      gamma: 0.8
transforms:
  - name: "rheed_segmentation.transforms.CLAHE"
    params:
      tile_grid_size: [8, 8]
  - name: "rheed_segmentation.transforms.CLAHE"
    params:
      tile_grid_size: [4, 4]
  - name: "rheed_segmentation.transforms.AutoScaleTransform"
  - name: "Resize"
    params:
      height: 135
      width: 180
  - name: "HorizontalFlip"
    target: "train"
    params:
      p: 0.5
  - name: "ToTensorV2"
